### PR TITLE
detail what happens to dashboard and webservice

### PR DESCRIPTION
**Pull request by dotcode**

### CODE REVIEW

**Comment by rowanmanning** [comment]
@hollsk, @joseluisbolos, and me have come up with a proposed edit. We're not comfortable with dropping the projects into maintenance mode immediately:

``` md
Nothing will change immediately with how these projects are supported. We'll still be responding to issues and feature requests in the same way.

Larger features may not be considered, but we've been in this state for some time – it's difficult to confidently make changes in these projects due to the [reasons outlined here](#history).

Once Pa11y Sidekick reaches `1.0.0`, pa11y-dashboard and pa11y-webservice will be deprecated (with a long support end date). At this point we will recommend the use of Pa11y Sidekick over either of these projects.
```

**Comment by dotcode** [comment]
Much better, I'm happy with that, as is @andrewmee.

**Comment by rowanmanning** [comment]
You didn't add my changes 😄

**Comment by dotcode** [comment]
Can't believe I did that! I'll blame trying to sort this from my phone in a pub, but still. Sheesh.

**Pull request merged**
